[workspace]

members = [
    "kernel",
    "bootloader",
    "kmain",
]

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = true

[profile.small]
inherits = "release"
opt-level = "s"
lto = true

[profile.unopt]
inherits = "dev"
opt-level = 0
