[package]
name = "kernel"
version = "0.1.0"
authors = ["Zachary Yedidia"]
edition = "2021"

[lib]
path = "lib.rs"
crate-type = ["rlib"]

[features]
default = ["kernel", "virt"]
kernel = []
monitor = []
virt = []
visionfive2 = []

[dependencies]
buddyalloc = "0.1.5"
