[build]
target = "riscv64imac-unknown-none-elf"
rustflags = ["-Adead_code"]
target-dir = ".target"

[profile.dev]
opt-level = 1
debug = true
panic = "abort"

[profile.release]
opt-level = 3
lto = true
panic = "abort"

[profile.small]
inherits = "release"
opt-level = "s"

[profile.unopt]
inherits = "dev"
opt-level = 0
panic = "abort"
