[build]
target = "riscv64imac-unknown-none-elf"
rustflags = ["-Adead_code", "-Aunused_variables"]
target-dir = ".target"

[profile.dev]
opt-level = 1
panic = "abort"

[profile.release]
opt-level = 3
lto = true
panic = "abort"

[profile.small]
inherits = "release"
opt-level = "s"

[profile.unopt]
inherits = "dev"
opt-level = 0
panic = "abort"
